import type {
  AppNotification,
  Person,
  Project,
  Task,
  TeamInvitation,
  TimeEntry,
  Workspace,
  WorkspaceMember,
} from "@/lib/types";

export const workspaces: Workspace[] = [
  {
    id: "prisma",
    name: "Prisma Agencia",
    memberCount: 4,
    role: "owner",
    archived: false,
    currency: "USD",
  },
];

export const people: Person[] = [
  {
    id: "martina",
    name: "Martina Silva",
    initials: "MS",
    color: "#6556EE",
    role: "Dirección de cuentas",
    email: "martina@prisma.agency",
  },
  {
    id: "diego",
    name: "Diego Núñez",
    initials: "DN",
    color: "#EF6A67",
    role: "Dirección de arte",
    email: "diego@prisma.agency",
  },
  {
    id: "lucia",
    name: "Lucía Reyes",
    initials: "LR",
    color: "#19A38C",
    role: "Copywriter",
    email: "lucia@prisma.agency",
  },
  {
    id: "tomas",
    name: "Tomás Costa",
    initials: "TC",
    color: "#D98B25",
    role: "Paid Media",
    email: "tomas@prisma.agency",
  },
];

export const projects: Project[] = [
  {
    id: "aura",
    name: "Lanzamiento Aura",
    color: "#6556EE",
    workspaceId: "prisma",
    archived: false,
  },
  {
    id: "brava",
    name: "Verano Brava",
    color: "#EF6A67",
    workspaceId: "prisma",
    archived: false,
  },
  {
    id: "marca-sur",
    name: "Marca Sur",
    color: "#19A38C",
    workspaceId: "prisma",
    archived: false,
  },
  {
    id: "nexo",
    name: "Always-on Nexo",
    color: "#3C8FD5",
    workspaceId: "prisma",
    archived: false,
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-1",
    code: "AG-142",
    title: "Adaptar campaña de lanzamiento a stories",
    description:
      "Preparar seis piezas verticales a partir del key visual aprobado. Incluir versiones con y sin precio para pauta y orgánico.",
    project: projects[0],
    parentTaskId: null,
    status: "en_progreso",
    priority: "urgente",
    assignee: people[1],
    client: "Aura Cosmética",
    clientEmail: "marketing@aura.com",
    dueDate: "2026-07-24",
    dueLabel: "Hoy, 18:00",
    updatedAt: "Hace 12 min",
    tags: ["Social", "Stories"],
    comments: [
      {
        id: "comment-1",
        author: people[0],
        body: "El cliente aprobó la dirección visual. Mantengamos el producto centrado y el claim arriba.",
        createdAt: "Hoy, 10:18",
      },
      {
        id: "comment-2",
        author: people[1],
        body: "Ya subí las primeras tres adaptaciones. Estoy cerrando las versiones con precio.",
        createdAt: "Hoy, 10:42",
      },
    ],
    attachments: [
      {
        id: "attachment-1",
        taskId: "task-1",
        name: "brief-stories.txt",
        size: 148,
        mimeType: "text/plain",
        storagePath: null,
        dataUrl:
          "data:text/plain;charset=utf-8,Brief%20de%20stories%20para%20la%20campa%C3%B1a%20Aura",
        createdAt: "Hoy, 09:45",
        uploader: people[0],
      },
    ],
  },
  {
    id: "task-2",
    code: "AG-147",
    title: "Cerrar copies para campaña de invierno",
    description:
      "Redactar concepto, copy principal y variantes cortas para Meta Ads. El tono debe ser cercano, optimista y directo.",
    project: projects[1],
    parentTaskId: null,
    status: "nuevo",
    priority: "alta",
    assignee: people[2],
    client: "Brava Bebidas",
    clientEmail: "equipo@brava.com",
    dueDate: "2026-07-25",
    dueLabel: "Mañana",
    updatedAt: "Hace 28 min",
    tags: ["Copy", "Campaña"],
    comments: [],
    attachments: [],
  },
  {
    id: "task-3",
    code: "AG-138",
    title: "Incorporar feedback al key visual",
    description:
      "El cliente pidió dar más presencia al producto, reducir el logo secundario y probar una alternativa con fondo marfil.",
    project: projects[2],
    parentTaskId: null,
    status: "esperando",
    priority: "media",
    assignee: people[1],
    client: "Marca Sur",
    dueDate: "2026-07-24",
    dueLabel: "Hoy",
    updatedAt: "Hace 1 h",
    tags: ["Diseño", "Key visual"],
    comments: [
      {
        id: "comment-3",
        author: people[0],
        body: "Dejé consolidado el feedback de la reunión. Necesitamos dos rutas para la revisión de las 16:00.",
        createdAt: "Hoy, 09:32",
      },
    ],
    attachments: [],
  },
  {
    id: "task-4",
    code: "AG-135",
    title: "Configurar pauta de Meta para agosto",
    description:
      "Preparar estructura de campañas, audiencias y distribución de presupuesto. Dejar todo en borrador para revisión.",
    project: projects[3],
    parentTaskId: null,
    status: "en_progreso",
    priority: "alta",
    assignee: people[3],
    client: "Nexo Educación",
    dueDate: "2026-07-28",
    dueLabel: "28 jul",
    updatedAt: "Hace 2 h",
    tags: ["Paid Media", "Meta"],
    comments: [],
    attachments: [],
  },
  {
    id: "task-5",
    code: "AG-150",
    title: "Exportar versión final del spot de 15 segundos",
    description:
      "Generar masters horizontal y vertical con subtítulos, placa legal y compresión para cada plataforma.",
    project: projects[1],
    parentTaskId: null,
    status: "nuevo",
    priority: "media",
    assignee: null,
    client: "Brava Bebidas",
    dueDate: "2026-07-25",
    dueLabel: "Mañana",
    updatedAt: "Hace 16 min",
    tags: ["Video", "Postproducción"],
    comments: [],
    attachments: [],
  },
  {
    id: "task-6",
    code: "AG-131",
    title: "Aprobar grilla de contenidos de agosto",
    description:
      "Revisión final de piezas, copies y fechas de publicación del calendario mensual.",
    project: projects[3],
    parentTaskId: null,
    status: "resuelto",
    priority: "baja",
    assignee: people[0],
    client: "Nexo Educación",
    dueDate: "2026-07-23",
    dueLabel: "23 jul",
    updatedAt: "Ayer",
    tags: ["Contenido", "Calendario"],
    comments: [],
    attachments: [],
  },
  {
    id: "task-7",
    code: "AG-140",
    title: "Entregar propuesta de rebranding",
    description:
      "Cerrar la presentación con las dos rutas de identidad, aplicaciones principales y racional creativo.",
    project: projects[2],
    parentTaskId: null,
    status: "en_progreso",
    priority: "urgente",
    assignee: people[1],
    client: "Marca Sur",
    dueDate: "2026-07-24",
    dueLabel: "Hoy, 16:00",
    updatedAt: "Hace 34 min",
    tags: ["Branding", "Presentación"],
    comments: [],
    attachments: [],
  },
  {
    id: "task-8",
    code: "AG-127",
    title: "Ajustar reporte de resultados del Q2",
    description:
      "Actualizar conclusiones, sumar benchmark de industria y traducir los aprendizajes a próximos pasos accionables.",
    project: projects[0],
    parentTaskId: null,
    status: "esperando",
    priority: "baja",
    assignee: people[3],
    client: "Aura Cosmética",
    dueDate: "2026-07-30",
    dueLabel: "30 jul",
    updatedAt: "Ayer",
    tags: ["Reporte", "Performance"],
    comments: [],
    attachments: [],
  },
  {
    id: "subtask-1",
    code: "AG-151",
    title: "Exportar versión sin precio",
    description: "",
    project: projects[0],
    parentTaskId: "task-1",
    status: "resuelto",
    priority: "media",
    assignee: people[1],
    client: "Aura Cosmética",
    dueDate: "2026-07-24",
    dueLabel: "Hoy",
    updatedAt: "Hace 20 min",
    tags: [],
    comments: [],
    attachments: [],
  },
  {
    id: "subtask-2",
    code: "AG-152",
    title: "Revisar safe areas para stories",
    description: "",
    project: projects[0],
    parentTaskId: "task-1",
    status: "en_progreso",
    priority: "alta",
    assignee: people[0],
    client: "Aura Cosmética",
    dueDate: "2026-07-24",
    dueLabel: "Hoy",
    updatedAt: "Hace 8 min",
    tags: [],
    comments: [],
    attachments: [],
  },
];

export const workspaceMembers: WorkspaceMember[] = people.map(
  (person, index) => ({
    workspaceId: "prisma",
    user: person,
    role: index === 0 ? "owner" : index === 1 ? "admin" : "agent",
    joinedAt: "Julio de 2026",
    hourlyRate: [65, 52, 42, 48][index],
  }),
);

export const timeEntries: TimeEntry[] = [
  {
    id: "time-1",
    workspaceId: "prisma",
    taskId: "task-1",
    taskCode: "AG-142",
    taskTitle: "Adaptar campaña de lanzamiento a stories",
    projectId: "aura",
    projectName: "Lanzamiento Aura",
    user: people[1],
    description: "Adaptaciones verticales y revisión de safe areas",
    startedAt: "2026-07-24T12:00:00.000Z",
    endedAt: "2026-07-24T14:15:00.000Z",
    durationSeconds: 8100,
    billable: true,
    hourlyRate: 52,
    createdAt: "Hoy",
  },
  {
    id: "time-2",
    workspaceId: "prisma",
    taskId: "task-3",
    taskCode: "AG-138",
    taskTitle: "Incorporar feedback al key visual",
    projectId: "marca-sur",
    projectName: "Marca Sur",
    user: people[1],
    description: "Ajustes de composición solicitados por cliente",
    startedAt: "2026-07-23T15:30:00.000Z",
    endedAt: "2026-07-23T17:00:00.000Z",
    durationSeconds: 5400,
    billable: true,
    hourlyRate: 52,
    createdAt: "Ayer",
  },
  {
    id: "time-3",
    workspaceId: "prisma",
    taskId: "task-4",
    taskCode: "AG-135",
    taskTitle: "Configurar pauta de Meta para agosto",
    projectId: "nexo",
    projectName: "Always-on Nexo",
    user: people[3],
    description: "Estructura de campañas y audiencias",
    startedAt: "2026-07-24T13:00:00.000Z",
    endedAt: "2026-07-24T14:45:00.000Z",
    durationSeconds: 6300,
    billable: true,
    hourlyRate: 48,
    createdAt: "Hoy",
  },
  {
    id: "time-4",
    workspaceId: "prisma",
    taskId: "task-6",
    taskCode: "AG-131",
    taskTitle: "Aprobar grilla de contenidos de agosto",
    projectId: "nexo",
    projectName: "Always-on Nexo",
    user: people[0],
    description: "Revisión interna no facturable",
    startedAt: "2026-07-23T13:00:00.000Z",
    endedAt: "2026-07-23T13:45:00.000Z",
    durationSeconds: 2700,
    billable: false,
    hourlyRate: 65,
    createdAt: "Ayer",
  },
];

export const invitations: TeamInvitation[] = [
  {
    id: "invite-1",
    workspaceId: "prisma",
    email: "sofia@prisma.agency",
    role: "agent",
    token: "demo-invite",
    createdAt: "Hoy",
    expiresAt: "2026-07-31T18:00:00.000Z",
    acceptedAt: null,
  },
];

export const notifications: AppNotification[] = [
  {
    id: "notification-1",
    title: "Nuevo comentario",
    body: "Diego comentó en “Adaptar campaña de lanzamiento a stories”.",
    createdAt: "Hace 12 min",
    readAt: null,
    taskId: "task-1",
  },
  {
    id: "notification-2",
    title: "Entrega próxima",
    body: "“Entregar propuesta de rebranding” vence hoy.",
    createdAt: "Hace 1 h",
    readAt: null,
    taskId: "task-7",
  },
];
