-- Taska para agencias: esquema inicial para Supabase/PostgreSQL.
-- Ejecutar con `supabase db push` o pegar en el SQL Editor de Supabase.

create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'team_role') then
    create type public.team_role as enum ('owner', 'admin', 'agent', 'viewer');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_status') then
    create type public.task_status as enum ('nuevo', 'en_progreso', 'esperando', 'resuelto');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_priority') then
    create type public.task_priority as enum ('urgente', 'alta', 'media', 'baja');
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  role text default 'Equipo creativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.team_role not null default 'agent',
  joined_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  name text not null,
  slug text not null,
  color text not null default '#5B4BEC',
  description text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, slug)
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  task_number bigint generated by default as identity,
  team_id uuid not null references public.teams(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  parent_task_id uuid references public.tasks(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 180),
  description text not null default '',
  status public.task_status not null default 'nuevo',
  priority public.task_priority not null default 'media',
  assignee_id uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  client_name text,
  client_email text,
  due_date date,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks
add column if not exists parent_task_id uuid
references public.tasks(id) on delete cascade;

create index if not exists tasks_team_id_idx on public.tasks(team_id);
create index if not exists tasks_project_id_idx on public.tasks(project_id);
create index if not exists tasks_parent_task_id_idx on public.tasks(parent_task_id);
create index if not exists tasks_assignee_id_idx on public.tasks(assignee_id);
create index if not exists tasks_status_priority_idx on public.tasks(status, priority);
create index if not exists tasks_due_date_idx on public.tasks(due_date);
create index if not exists comments_task_id_idx on public.comments(task_id);
create index if not exists team_members_user_id_idx on public.team_members(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_team_member(candidate_team_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.team_members
    where team_id = candidate_team_id
      and user_id = auth.uid()
  );
$$;

create or replace function public.is_team_admin(candidate_team_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.team_members
    where team_id = candidate_team_id
      and user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$;

alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.comments enable row level security;

drop policy if exists "profiles visible to teammates" on public.profiles;
create policy "profiles visible to teammates"
on public.profiles for select
to authenticated
using (
  id = auth.uid()
  or exists (
    select 1
    from public.team_members mine
    join public.team_members theirs on theirs.team_id = mine.team_id
    where mine.user_id = auth.uid() and theirs.user_id = profiles.id
  )
);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "members view teams" on public.teams;
create policy "members view teams"
on public.teams for select
to authenticated
using (public.is_team_member(id));

drop policy if exists "users create teams" on public.teams;
create policy "users create teams"
on public.teams for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "admins update teams" on public.teams;
create policy "admins update teams"
on public.teams for update
to authenticated
using (public.is_team_admin(id))
with check (public.is_team_admin(id));

drop policy if exists "members view memberships" on public.team_members;
create policy "members view memberships"
on public.team_members for select
to authenticated
using (public.is_team_member(team_id));

drop policy if exists "admins manage memberships" on public.team_members;
create policy "admins manage memberships"
on public.team_members for all
to authenticated
using (public.is_team_admin(team_id))
with check (public.is_team_admin(team_id));

drop policy if exists "members view projects" on public.projects;
create policy "members view projects"
on public.projects for select
to authenticated
using (public.is_team_member(team_id));

drop policy if exists "admins manage projects" on public.projects;
create policy "admins manage projects"
on public.projects for all
to authenticated
using (public.is_team_admin(team_id))
with check (public.is_team_admin(team_id));

drop policy if exists "members view tasks" on public.tasks;
create policy "members view tasks"
on public.tasks for select
to authenticated
using (public.is_team_member(team_id));

drop policy if exists "members create tasks" on public.tasks;
create policy "members create tasks"
on public.tasks for insert
to authenticated
with check (public.is_team_member(team_id));

drop policy if exists "members update tasks" on public.tasks;
create policy "members update tasks"
on public.tasks for update
to authenticated
using (public.is_team_member(team_id))
with check (public.is_team_member(team_id));

drop policy if exists "admins delete tasks" on public.tasks;
create policy "admins delete tasks"
on public.tasks for delete
to authenticated
using (public.is_team_admin(team_id));

drop policy if exists "members view comments" on public.comments;
create policy "members view comments"
on public.comments for select
to authenticated
using (
  exists (
    select 1 from public.tasks
    where tasks.id = comments.task_id
      and public.is_team_member(tasks.team_id)
  )
);

drop policy if exists "members create comments" on public.comments;
create policy "members create comments"
on public.comments for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1 from public.tasks
    where tasks.id = comments.task_id
      and public.is_team_member(tasks.team_id)
  )
);

drop policy if exists "authors update comments" on public.comments;
create policy "authors update comments"
on public.comments for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "authors delete comments" on public.comments;
create policy "authors delete comments"
on public.comments for delete
to authenticated
using (author_id = auth.uid());

create or replace function public.bootstrap_workspace()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_team_id uuid;
  new_team_id uuid;
  aura_project_id uuid;
  brava_project_id uuid;
  nexo_project_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.profiles (id, full_name)
  values (auth.uid(), 'Dirección de cuentas')
  on conflict (id) do nothing;

  select team_id into existing_team_id
  from public.team_members
  where user_id = auth.uid()
  order by joined_at
  limit 1;

  if existing_team_id is not null then
    return existing_team_id;
  end if;

  insert into public.teams (name, slug, created_by)
  values (
    'Prisma Agencia',
    'prisma-agency-' || substr(replace(auth.uid()::text, '-', ''), 1, 8),
    auth.uid()
  )
  returning id into new_team_id;

  insert into public.team_members (team_id, user_id, role)
  values (new_team_id, auth.uid(), 'owner');

  insert into public.projects (team_id, name, slug, color)
  values (new_team_id, 'Lanzamiento Aura', 'lanzamiento-aura', '#6556EE')
  returning id into aura_project_id;

  insert into public.projects (team_id, name, slug, color)
  values (new_team_id, 'Verano Brava', 'verano-brava', '#EF6A67')
  returning id into brava_project_id;

  insert into public.projects (team_id, name, slug, color)
  values (new_team_id, 'Always-on Nexo', 'always-on-nexo', '#3C8FD5')
  returning id into nexo_project_id;

  insert into public.tasks (
    team_id, project_id, title, description, status, priority,
    assignee_id, client_name, due_date, tags
  )
  values
    (
      new_team_id, aura_project_id, 'Adaptar campaña de lanzamiento a stories',
      'Preparar seis piezas verticales a partir del key visual aprobado.',
      'en_progreso', 'urgente', auth.uid(), 'Aura Cosmética',
      current_date, array['Social', 'Stories']
    ),
    (
      new_team_id, brava_project_id, 'Cerrar copies para campaña de invierno',
      'Redactar concepto, copy principal y variantes para Meta Ads.',
      'nuevo', 'alta', auth.uid(), 'Brava Bebidas',
      current_date + 1, array['Copy', 'Campaña']
    ),
    (
      new_team_id, nexo_project_id, 'Configurar pauta de Meta para agosto',
      'Preparar campañas, audiencias y distribución de presupuesto.',
      'nuevo', 'media', null, 'Nexo Educación',
      current_date + 1, array['Paid Media', 'Meta']
    );

  return new_team_id;
end;
$$;

revoke all on function public.bootstrap_workspace() from public;
grant execute on function public.bootstrap_workspace() to authenticated;

create or replace function public.create_workspace(workspace_name text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_team_id uuid;
  normalized_name text := trim(workspace_name);
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if char_length(normalized_name) < 2 or char_length(normalized_name) > 80 then
    raise exception 'Workspace name must contain between 2 and 80 characters';
  end if;

  insert into public.profiles (id, full_name)
  values (auth.uid(), 'Integrante')
  on conflict (id) do nothing;

  insert into public.teams (name, slug, created_by)
  values (
    normalized_name,
    'workspace-'
      || substr(replace(auth.uid()::text, '-', ''), 1, 8)
      || '-'
      || floor(extract(epoch from clock_timestamp()) * 1000)::bigint,
    auth.uid()
  )
  returning id into new_team_id;

  insert into public.team_members (team_id, user_id, role)
  values (new_team_id, auth.uid(), 'owner');

  return new_team_id;
end;
$$;

revoke all on function public.create_workspace(text) from public;
grant execute on function public.create_workspace(text) to authenticated;
